"use client";

import { Download, FileType2, Share2 } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/PageHeader";
import { formatDateTime, formatBytes } from "@/lib/utils";

const REPORT = {
  id: "R-1",
  title: "Q2 Executive Summary",
  role: "ciso",
  generated_at: new Date().toISOString(),
  generated_by: "ai.bot",
  format: "pdf",
  size_bytes: 824_000,
};

const SECTIONS = [
  { title: "Executive Summary", body: "Across the second quarter, the security posture remains strong. We tracked 352 findings across 47 scans, with 12 critical issues remediated within SLA. MTTR improved 18% quarter over quarter. Key risk: third-party SaaS exposure (see section 4)." },
  { title: "Top Risks", body: "1) Public S3 bucket exposure recovered same-day. 2) Domain admin Kerberoasting attempt on corp.local — kerberos ticket lifetime reduced. 3) Outdated TLS 1.0 endpoints retired in legacy SaaS portal." },
  { title: "Bug Bounty", body: "$142,500 paid out across 38 confirmed submissions. Top hunter @h4ck3rb33 contributed 8 high-impact reports. Average triage time: 26h." },
  { title: "Roadmap & Recommendations", body: "Adopt CSPM tooling for AWS coverage. Expand Red Team simulations to internal AD. Pilot zero-trust on developer endpoints." },
];

export default function ReportDetailPage({ params }: { params: { id: string } }) {
  return (
    <div className="space-y-6">
      <PageHeader
        title={REPORT.title}
        description={`Audience: ${REPORT.role.toUpperCase()} · Generated by ${REPORT.generated_by}`}
        breadcrumbs={[
          { label: "Reports", href: "/reports" },
          { label: params.id },
        ]}
        action={
          <div className="flex gap-2">
            <button type="button" className="btn-secondary" onClick={() => toast("Share link copied")}>
              <Share2 className="h-4 w-4" /> Share
            </button>
            <button type="button" className="btn-secondary" onClick={() => toast.success("Downloading HTML")}>
              <FileType2 className="h-4 w-4" /> HTML
            </button>
            <button type="button" className="btn-primary" onClick={() => toast.success("Downloading PDF")}>
              <Download className="h-4 w-4" /> PDF
            </button>
          </div>
        }
      />

      <div className="panel p-6 grid grid-cols-1 md:grid-cols-3 gap-3">
        <div>
          <p className="label">Generated</p>
          <p className="text-sm">{formatDateTime(REPORT.generated_at)}</p>
        </div>
        <div>
          <p className="label">Format</p>
          <p className="text-sm font-mono uppercase">{REPORT.format}</p>
        </div>
        <div>
          <p className="label">Size</p>
          <p className="text-sm">{formatBytes(REPORT.size_bytes)}</p>
        </div>
      </div>

      <article className="panel p-8 prose prose-invert max-w-none">
        {SECTIONS.map((section) => (
          <section key={section.title} className="mb-6">
            <h2 className="text-lg font-bold text-fg mb-2">{section.title}</h2>
            <p className="text-sm text-fg-muted leading-relaxed">{section.body}</p>
          </section>
        ))}
      </article>
    </div>
  );
}
